import { useEffect, useState } from 'react'
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth'
import { auth } from '../firebase'
import { leftHandRanking, rightHandRanking } from '../data'
import AddParticipantPanel from './AddParticipantPanel'
import DeleteEventsPanel from './DeleteEventsPanel'
import EventResultPanel from './EventResultPanel'
import FutureEventPanel from './FutureEventPanel'

function CountryInput({ countries, value, onChange, label }) {
  const [query, setQuery] = useState(value.replace(/^[\p{Emoji_Presentation}\p{Extended_Pictographic}]+\s*/u, ''))
  useEffect(() => setQuery(value.replace(/^[\p{Emoji_Presentation}\p{Extended_Pictographic}]+\s*/u, '')), [value])
  return <label className="country-input">{label}<input list="country-options" value={query} placeholder="Buscar país" onChange={(event) => { const next = event.target.value; setQuery(next); const match = countries.find((country) => country.replace(/^[\p{Emoji_Presentation}\p{Extended_Pictographic}]+\s*/u, '').toLowerCase() === next.toLowerCase()); if (match) onChange(match) }} /></label>
}

function SearchPlayer({ label, rankings, value, onChange }) {
  const [query, setQuery] = useState('')
  const options = rankings.filter((fighter) => !query || `${fighter.name} ${fighter.alias}`.toLowerCase().includes(query.toLowerCase()))
  return <label className="event-player-picker">{label}<input type="search" placeholder="Buscar jugador" value={query} onChange={(event) => setQuery(event.target.value)} /><select value={value} onChange={(event) => onChange(event.target.value)} required><option value="">Selecciona un jugador</option>{options.map((fighter) => <option key={`${fighter.name}-${fighter.rank}`} value={`${fighter.name}-${fighter.rank}`}>{fighter.rank}. {fighter.name} · {fighter.alias}</option>)}</select></label>
}

function RankingEditor({ draft, side, countries, query, setQuery, rankInputs, updateRankInput, moveRank, updateFighter, removeFighter, onSave, onDiscard }) {
  const list = draft[side]
  const visible = list.map((fighter, index) => ({ fighter, index })).filter(({ fighter }) => !query || `${fighter.rank} ${fighter.name} ${fighter.alias}`.toLowerCase().includes(query.toLowerCase()))
  return <>
    <div className="admin-toolbar"><div className="toggle-group admin-toggle-group"><span className={`toggle-slider admin-toggle-slider ${side === 'left' ? 'left' : 'right'}`} /><button type="button" className={`toggle admin-toggle ${side === 'left' ? 'active' : ''}`} onClick={() => side !== 'left' && onDiscard('left')}>Izquierda</button><button type="button" className={`toggle admin-toggle ${side === 'right' ? 'active' : ''}`} onClick={() => side !== 'right' && onDiscard('right')}>Derecha</button></div><div className="admin-actions"><button type="button" className="primary-btn" onClick={onSave}>Guardar cambios</button><button type="button" className="ghost-btn" onClick={() => onDiscard(side)}>Descartar cambios</button></div></div>
    <input className="ranking-search" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nombre, alias o posición" />
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Pos.</th><th>Nombre</th><th>Alias</th><th>País</th><th>Acciones</th></tr></thead><tbody>{visible.map(({ fighter, index }) => <tr key={`${fighter.name}-${index}`}><td><input className="rank-number-input" type="number" min="1" max={list.length} value={rankInputs[side][index] ?? String(fighter.rank)} onChange={(event) => updateRankInput(index, event.target.value)} onBlur={(event) => moveRank(index, event.target.value)} /></td><td><input value={fighter.name} onChange={(event) => updateFighter(index, 'name', event.target.value)} /></td><td><input value={fighter.alias} onChange={(event) => updateFighter(index, 'alias', event.target.value)} /></td><td><CountryInput countries={countries} value={fighter.country} label={`País de ${fighter.name}`} onChange={(value) => updateFighter(index, 'country', value)} /></td><td><button type="button" className="delete-fighter" onClick={() => removeFighter(index)}>×</button></td></tr>)}</tbody></table></div>
    <div className="admin-mobile-list">{visible.map(({ fighter, index }) => <article className="admin-fighter-card" key={`${fighter.name}-${index}`}><div className="admin-fighter-header"><label>Pos.<input className="rank-number-input" type="number" min="1" max={list.length} value={rankInputs[side][index] ?? String(fighter.rank)} onChange={(event) => updateRankInput(index, event.target.value)} onBlur={(event) => moveRank(index, event.target.value)} /></label><button type="button" className="delete-fighter" onClick={() => removeFighter(index)}>×</button></div><label>Nombre<input value={fighter.name} onChange={(event) => updateFighter(index, 'name', event.target.value)} /></label><label>Alias<input value={fighter.alias} onChange={(event) => updateFighter(index, 'alias', event.target.value)} /></label><CountryInput countries={countries} value={fighter.country} label="País" onChange={(value) => updateFighter(index, 'country', value)} /></article>)}</div>
  </>
}

export default function AdminPage({ rankings, events, futureEvents, countries, onSave, onRecord, onAddFuture, onDeleteEvent, onDeleteFuture }) {
  const fallback = { left: leftHandRanking, right: rightHandRanking }
  const initial = { left: rankings.left?.length ? rankings.left : fallback.left, right: rankings.right?.length ? rankings.right : fallback.right }
  const [adminUser, setAdminUser] = useState(null); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [side, setSide] = useState('left'); const [draft, setDraft] = useState(initial); const [rankInputs, setRankInputs] = useState({ left: initial.left.map((fighter) => String(fighter.rank)), right: initial.right.map((fighter) => String(fighter.rank)) }); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [section, setSection] = useState('ranking')
  useEffect(() => onAuthStateChanged(auth, setAdminUser), [])
  useEffect(() => { if (rankings.left?.length && rankings.right?.length) { setDraft(rankings); setRankInputs({ left: rankings.left.map((fighter) => String(fighter.rank)), right: rankings.right.map((fighter) => String(fighter.rank)) }) } }, [rankings.left, rankings.right])
  if (!adminUser) return <section className="admin-login standalone-page"><p className="eyebrow alt">Acceso restringido</p><h2>Administración del ranking</h2><form className="login-form" onSubmit={async (event) => { event.preventDefault(); try { await signInWithEmailAndPassword(auth, email, password) } catch { setStatus('No se pudo iniciar sesión.') } }}><label>Correo<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Contraseña<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{status ? <p className="login-error">{status}</p> : null}<button type="submit" className="primary-btn">Entrar</button></form></section>
  const updateFighter = (index, field, value) => setDraft((current) => ({ ...current, [side]: current[side].map((fighter, i) => i === index ? { ...fighter, [field]: value } : fighter) }))
  const updateRankInput = (index, value) => setRankInputs((current) => ({ ...current, [side]: current[side].map((rank, i) => i === index ? value : rank) }))
  const moveRank = (index, value) => { const target = Number(value); if (!Number.isInteger(target)) return; const reordered = [...draft[side]]; const [fighter] = reordered.splice(index, 1); reordered.splice(Math.min(Math.max(target, 1), reordered.length + 1) - 1, 0, fighter); const ranked = reordered.map((entry, rankIndex) => ({ ...entry, rank: rankIndex + 1 })); setDraft((current) => ({ ...current, [side]: ranked })); setRankInputs((current) => ({ ...current, [side]: ranked.map((entry) => String(entry.rank)) })); setStatus('Posición modificada. Guarda los cambios.') }
  const removeFighter = (index) => setDraft((current) => ({ ...current, [side]: current[side].filter((_, i) => i !== index).map((fighter, rankIndex) => ({ ...fighter, rank: rankIndex + 1 })) }))
  const save = async () => { await onSave(draft); setStatus('Cambios guardados en Firebase.') }
  const addParticipant = async ({ side: targetSide, name, alias, country, rank }) => { const list = draft[targetSide]; const next = [...list]; next.splice(Math.max(0, Math.min(rank - 1, list.length)), 0, { name: name.trim(), alias: alias.trim(), country }); const ranked = next.map((fighter, index) => ({ ...fighter, rank: index + 1 })); const nextRankings = { ...draft, [targetSide]: ranked }; await onSave(nextRankings); setDraft(nextRankings); setRankInputs((current) => ({ ...current, [targetSide]: ranked.map((fighter) => String(fighter.rank)) })); setStatus('Participante añadido y guardado en Firebase.') }
  return <section className="admin-page standalone-page"><div className="section-heading admin-heading"><div><p className="eyebrow alt">Panel privado</p><h2>{section === 'ranking' ? 'Editar ranking' : 'Administración de eventos'}</h2></div><button type="button" className="ghost-btn" onClick={() => signOut(auth)}>Cerrar sesión</button></div><div className="admin-section-tabs"><button type="button" className={`admin-section-tab ${section === 'ranking' ? 'active' : ''}`} onClick={() => setSection('ranking')}>Editar ranking</button><button type="button" className={`admin-section-tab ${section === 'add' ? 'active' : ''}`} onClick={() => setSection('add')}>Añadir participante</button><button type="button" className={`admin-section-tab ${section === 'results' ? 'active' : ''}`} onClick={() => setSection('results')}>Registrar resultados</button><button type="button" className={`admin-section-tab ${section === 'event' ? 'active' : ''}`} onClick={() => setSection('event')}>Registrar evento</button><button type="button" className={`admin-section-tab ${section === 'modify' ? 'active' : ''}`} onClick={() => setSection('modify')}>Modificar resultados</button><button type="button" className={`admin-section-tab ${section === 'future' ? 'active' : ''}`} onClick={() => setSection('future')}>Modificar próximos</button></div>{section === 'ranking' ? <RankingEditor draft={draft} side={side} countries={countries} query={query} setQuery={setQuery} rankInputs={rankInputs} updateRankInput={updateRankInput} moveRank={moveRank} updateFighter={updateFighter} removeFighter={removeFighter} onSave={save} onDiscard={(nextSide) => { setSide(nextSide); setDraft(initial); setQuery('') }} /> : section === 'add' ? <AddParticipantPanel rankings={draft} countries={countries} onAdd={addParticipant} /> : section === 'results' ? <EventResultPanel rankings={draft} futureEvents={futureEvents} onRecord={onRecord} /> : section === 'event' ? <FutureEventPanel rankings={draft} onAdd={onAddFuture} /> : section === 'modify' ? <DeleteEventsPanel items={events} onDelete={onDeleteEvent} /> : <DeleteEventsPanel items={futureEvents} future onDelete={onDeleteFuture} />}{status ? <p className="save-status">{status}</p> : null}</section>
}
