import { useState } from 'react'

function Picker({ label, rankings, value, onChange }) { const [query, setQuery] = useState(''); const options = rankings.filter((f) => !query || `${f.name} ${f.alias}`.toLowerCase().includes(query.toLowerCase())); return <label className="event-player-picker">{label}<input type="search" placeholder="Buscar jugador" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={value} onChange={(e) => onChange(e.target.value)} required><option value="">Selecciona un jugador</option>{options.map((f) => <option key={`${f.name}-${f.rank}`} value={`${f.name}-${f.rank}`}>{f.rank}. {f.name}</option>)}</select></label> }

export default function EventResultPanel({ rankings, futureEvents, onRecord }) {
  const [hand, setHand] = useState('left'); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [a, setA] = useState(''); const [b, setB] = useState(''); const [scoreA, setScoreA] = useState(''); const [scoreB, setScoreB] = useState(''); const [winner, setWinner] = useState(''); const [held, setHeld] = useState('yes'); const [notes, setNotes] = useState(''); const [status, setStatus] = useState(''); const list = rankings[hand]; const retador = list.find((f) => `${f.name}-${f.rank}` === a); const oponente = list.find((f) => `${f.name}-${f.rank}` === b); const future = futureEvents.find((e) => e.retador === retador?.name && e.oponente === oponente?.name && e.hand === (hand === 'left' ? 'Izquierda' : 'Derecha'))
  const submit = async (e) => { e.preventDefault(); if (!retador || !oponente || a === b) return; try { await onRecord({ date, hand, retador, oponente, wasHeld: held === 'yes', score: `${scoreA}-${scoreB}`, winner: winner === a ? retador : oponente, notes, futureEvent: future }); setStatus('Evento guardado en la historia.') } catch { setStatus('No se pudo guardar el evento.') } }
  return <form className="event-results-form" onSubmit={submit}><div className="event-results-heading"><div><p className="eyebrow alt">Resultados</p><h3>Registrar resultado</h3></div></div><div className="event-results-grid"><label>Fecha<input type="date" value={date} onChange={(e) => setDate(e.target.value)} required /></label><label>Mano<select value={hand} onChange={(e) => { setHand(e.target.value); setA(''); setB('') }}><option value="left">Izquierda</option><option value="right">Derecha</option></select></label><Picker label="Retador" rankings={list} value={a} onChange={setA} /><Picker label="Oponente" rankings={list} value={b} onChange={setB} /><label>¿Se celebró?<select value={held} onChange={(e) => setHeld(e.target.value)}><option value="yes">Sí</option><option value="no">No</option></select></label>{held === 'yes' ? <><label>Puntos retador<input type="number" min="0" max="7" value={scoreA} onChange={(e) => setScoreA(e.target.value)} required /></label><label>Puntos oponente<input type="number" min="0" max="7" value={scoreB} onChange={(e) => setScoreB(e.target.value)} required /></label><label>Ganador<select value={winner} onChange={(e) => setWinner(e.target.value)} required><option value="">Selecciona ganador</option><option value={a}>{retador?.name}</option><option value={b}>{oponente?.name}</option></select></label></> : null}<label className="event-notes-field">Notas<textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows="3" /></label></div>{status ? <p className="save-status">{status}</p> : null}<button type="submit" className="primary-btn">Guardar resultado</button></form>
}
